main :
  watch : true
blockchain :
  contract : ContractFHWJcunJkSrGuSQhJiYPLxqkHXacZFC3Pkig8GFS4K6o
  server : http://52.192.65.220:30001/
database :
  server : 172.31.40.196:27017
  name : lucky_bet
