main :
  watch : false
  nonce : http://172.31.40.196:12345/nonce
blockchain :
  contract : Contract7MdF4Ppqj2hX2Z9yuaqS7gQakVDJbnpDRi6pPKLDFNXp
  server : http://52.192.65.220:30001/
database :
  server : 172.31.40.196:27017
  name : lucky_bet
