main :
  watch : false
  nonce : http://172.31.40.196:12345/nonce
blockchain :
  contract : ContractFtLmoyPtv7HuZzPoTcUtjKjtGoB493KVTHATpHDT4fjd
  server : http://localhost:80/
database :
  server : 172.31.40.196:27017
  name : lucky_bet
