main :
  watch : false
  nonce : http://172.31.40.196:12345/nonce
blockchain :
  contract : Contract5Q62hpocqpTtYSaDuRJJpfSRqqGVT5BmaR4EKfNPjBsK
  server : http://52.192.65.220:30001/
database :
  server : 172.31.40.196:27017
  name : lucky_bet
