main :
  watch : true
  nonce : http://172.31.40.196:12345/nonce
blockchain :
  contract : ContractGN8G1dj9VRjyq5Q6W3xWSRGmKJBHtVHSxYB2VnNqXSjm
  server : http://52.192.65.220:30001/
database :
  server : 172.31.40.196:27017
  name : lucky_bet
