main :
  watch : true
blockchain :
  contract : ContractGtkp1UmaL7BfPeRaisL3gc1MasTL2MqesnPJBx191Z1y
  server : http://54.95.136.154:30001/
database :
  server : 172.31.40.196:27017
  name : lucky_bet
