main :
  watch : false
  nonce : http://172.31.40.196:12345/nonce
blockchain :
  contract : Contract8xd4hE2JxYyMupk1j45muyLZQ87NxXbg73usLT6XcZhd
  server : http://localhost:80/
database :
  server : 172.31.40.196:27017
  name : lucky_bet
