main :
  watch : false
  nonce : http://172.31.40.196:12345/nonce
blockchain :
  contract : Contract66AsxRj68YioA9Hw68RnL45Nz714udHLW5aVDDnwYZMb
  server : http://localhost:80/
database :
  server : 172.31.40.196:27017
  name : lucky_bet
