main :
  watch : false
  nonce : http://172.31.40.196:12345/nonce
blockchain :
  contract : Contract9UPxoDYD7CVpMFxySLHKp2NhV8qCL4AG94F6chB853rR
  server : http://localhost:80/
database :
  server : 172.31.40.196:27017
  name : lucky_bet
